useDotenv: true

service: the-name-card
frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs18.x
    region: ap-southeast-1
    httpApi:
        cors: true
        authorizers:
            jwtAuthorizer:
                type: request
                functionName: authorize

functions:
    signToken:
        handler: src/functions/auth.signToken
        events:
            - httpApi:
                  path: /thenamecard/signToken
                  method: post

    createUser:
        handler: src/functions/db.createUser
        events:
            - httpApi:
                  path: /thenamecard/createUser
                  method: post
                  authorizer:
                      name: jwtAuthorizer

    createProfile:
        handler: src/functions/db.createProfile
        events:
            - httpApi:
                  path: /thenamecard/createProfile
                  method: post
                  authorizer:
                      name: jwtAuthorizer

    getPresignedUrl:
        handler: src/functions/s3.getPresignedUrl
        events:
            - httpApi:
                  path: /thenamecard/getPresignedUrl
                  method: post
                  authorizer:
                      name: jwtAuthorizer

    signIn:
        handler: src/functions/auth.signIn
        events:
            - httpApi:
                  path: /thenamecard/signin
                  method: post

    authorize:
        handler: src/functions/auth.authorize

plugins:
    - serverless-plugin-typescript
    - serverless-dotenv-plugin
