useDotenv: true

service: the-name-card
frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs18.x
    region: ap-southeast-1
    httpApi:
        authorizers:
            jwtAuthorizer:
                type: request
                functionName: authorize

functions:
    signToken:
        handler: src/functions/auth.signToken
        events:
            - httpApi:
                  path: /thenamecard/signToken
                  method: post

    testDb:
        handler: src/functions/db.test
        events:
            - httpApi:
                  path: /thenamecard/testdb
                  method: post

    authorize:
        handler: src/functions/auth.authorize

plugins:
    - serverless-plugin-typescript
    - serverless-dotenv-plugin
