useDotenv: true

service: the-name-card
frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs18.x
    region: ap-southeast-1

functions:
    testing:
        handler: src/functions/test.handler
        events:
            - httpApi:
                  path: /thenamecard/test
                  method: get

plugins:
    - serverless-plugin-typescript
    - serverless-dotenv-plugin
