useDotenv: true

service: the-name-card
frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs18.x
    region: ap-southeast-1

functions:
    signToken:
        handler: src/functions/auth.signToken
        events:
            - httpApi:
                  path: /thenamecard/signToken
                  method: post

plugins:
    - serverless-plugin-typescript
    - serverless-dotenv-plugin
